version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: db_project_mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'

    volumes:
      - data:/var/lib/mysql
volumes:
  data: